# Generated by Django 3.1.7 on 2021-03-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20210329_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='kurs',
            name='kategoria',
        ),
    ]
