# Generated by Django 3.1.7 on 2021-03-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20210329_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
