# Generated by Django 3.1.7 on 2021-03-29 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20210329_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='kategoria',
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
    ]
