# Generated by Django 3.1.7 on 2021-03-29 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0007_auto_20210329_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_kategorii', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'kategorie',
                'db_table': 'kategorie',
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256)),
                ('kategoria', models.ForeignKey(db_column='nazwa_kategorii', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='links.kategoria')),
            ],
            options={
                'verbose_name_plural': 'kursy',
                'db_table': 'kursy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('hiperlacze', models.CharField(max_length=256)),
                ('tutul', models.CharField(max_length=256)),
                ('dlugosc', models.BigIntegerField()),
                ('kurs', models.ForeignKey(db_column='nazwa', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='links.kurs')),
            ],
            options={
                'verbose_name_plural': 'filmy',
                'db_table': 'filmy',
                'managed': True,
            },
        ),
    ]
