# Generated by Django 3.1.7 on 2021-04-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_auto_20210421_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='opis',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
